# Generated by Django 5.0.6 on 2025-02-18 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.URLField(default='https://ibb.co.com/zHByVWC5', max_length=250)),
                ('full_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.URLField(default='https://ibb.co.com/zHByVWC5', max_length=250)),
                ('mobile_no', models.CharField(max_length=16)),
                ('full_address', models.CharField(max_length=250)),
            ],
        ),
    ]
