# Generated by Django 5.0.6 on 2025-02-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.URLField(default='https://ibb.co.com/jZhrJtTS', max_length=250)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('hotline', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
    ]
